import type { Metadata } from "next";

import "the-new-css-reset";
import "@/styles/global.css";

import clsx from "clsx";
import localFont from "next/font/local";
import { Header } from "@/components/elements/Header/Header";

const myFont = localFont({
    src: "../assets/font/SourceHanSansJP-VF.otf.woff2",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={clsx(myFont.className)}>
                <Header />
                {children}
            </body>
        </html>
    );
}
